# Copyright (c) 2022-2025, PostgreSQL Global Development Group

backend_sources += files(
  'flux_dirtymap.c',
  'flux_fsm.c',
  'flux_handler.c',
  'flux_operations.c',
  'flux_tuple.c',
  'flux_mvcc.c',
  'flux_stats.c',
  'flux_xlog.c',
  'flux_lock.c',
  'flux_slot.c',
  'flux_vm.c',
  'flux_undo.c',
  'flux_relundo.c',
  'flux_pvs.c',
)