# Copyright (c) 2022-2026, PostgreSQL Global Development Group

backend_sources += files(
  'atm.c',
  'logical_revert_worker.c',
  'slog.c',
  'slog_flathash.c',
  'slog_tuple.c',
  'undo.c',
  'undo_bufmgr.c',
  'undo_xlog.c',
  'undoapply.c',
  'undobuffer.c',
  'undoinsert.c',
  'undolog.c',
  'undorecord.c',
  'undormgr.c',
  'undostats.c',
  'undoworker.c',
  'xactundo.c',
  'perbackend/pbu_undolog.c',
  'perbackend/pbu_undofile.c',
  'perbackend/pbu_undorecord.c',
  'perbackend/pbu_undoinsert.c',
  'perbackend/pbu_undoaction.c',
  'perbackend/pbu_undoactionxlog.c',
  'perbackend/pbu_undorequest.c',
  'perbackend/pbu_undodiscard.c',
  'perbackend/pbu_discardworker.c',
  'perbackend/pbu_undoworker.c',
  'perbackend/pbu_recovery.c',
  'perbackend/pbu_helpers.c',
)
