#!/usr/bin/perl
#----------------------------------------------------------------------
#
# Generate guc_accessors.h from guc_parameters.dat.
#
# This emits the typed GUC accessor layer used by the threaded-runtime
# (xtc) work -- see docs/threading/F3_GUC_ACCESSORS.md.  For every GUC
# parameter it generates a token macro
#
#     #define GUC_<variable>  (<variable>)
#
# that names the GUC's backing storage, plus a small fixed set of typed
# identity accessors
#
#     GetGUCBool(x)   GetGUCInt(x)   GetGUCReal(x)
#     GetGUCString(x) GetGUCEnum(x)
#
# A direct read of a GUC global such as `work_mem` is rewritten (by the
# mechanical Coccinelle sweep in src/tools/cocci/guc_accessors.cocci) to
# `GetGUCInt(GUC_work_mem)`.  In the process model this is a zero-cost
# identity -- it expands straight back to the original global read -- so
# the generated code is byte-for-byte equivalent.  The accessor is the
# single chokepoint where, under the thread-per-connection model, the
# read can later be redirected to thread-local / xtc_cfg storage without
# touching any of the call sites again.
#
# Declarations and assignments of the backing globals are intentionally
# NOT routed through this layer: the GUC machinery (guc.c, guc_tables.c,
# guc_funcs.c) owns the storage and writes it through the &variable
# pointers in the generated GUC table.
#
# Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
#
# src/backend/utils/misc/gen_guc_accessors.pl
#
#----------------------------------------------------------------------

use strict;
use warnings FATAL => 'all';

use FindBin;
use lib "$FindBin::RealBin/../../catalog";
use Catalog;

die "Usage: $0 INPUT_FILE OUTPUT_FILE\n" unless @ARGV == 2;
my ($input_fname, $output_fname) = @ARGV;

my $parse = Catalog::ParseData($input_fname);

# Map GUC type -> the typed accessor used to read it.
my %accessor_for = (
	bool => 'GetGUCBool',
	int => 'GetGUCInt',
	real => 'GetGUCReal',
	string => 'GetGUCString',
	enum => 'GetGUCEnum',);

open my $ofh, '>', $output_fname or die "could not open $output_fname: $!";

print_boilerplate($ofh, $output_fname);

print $ofh <<'EOM';

#ifndef GUC_ACCESSORS_H
#define GUC_ACCESSORS_H

/*
 * Typed GUC read accessors.
 *
 * In the process model these are identity wrappers and compile away to a
 * plain read of the backing global.  They exist so the threaded runtime can
 * later redirect GUC reads (e.g. to thread-local or xtc_cfg storage) at a
 * single point, without re-touching the ~hundreds of call sites.
 *
 * Use the typed accessor matching the GUC's declared type; the argument is
 * the GUC_<variable> token defined further down (which names the backing
 * global).  Example: GetGUCInt(GUC_work_mem).
 */
#define GetGUCBool(x)	(x)
#define GetGUCInt(x)	(x)
#define GetGUCReal(x)	(x)
#define GetGUCString(x) (x)
#define GetGUCEnum(x)	(x)

EOM

print $ofh "/*\n";
print $ofh " * GUC_<variable> tokens -- one per GUC parameter, naming the backing\n";
print $ofh " * storage global.  Generated from guc_parameters.dat; keep call sites\n";
print $ofh " * using the GetGUC<Type>() accessors above rather than the raw global.\n";
print $ofh " */\n";

my %seen;
foreach my $entry (@{$parse})
{
	my $type = $entry->{type} // '';
	my $var = $entry->{variable};

	# Skip incomplete rows defensively; gen_guc_tables.pl validates fully.
	next unless defined $var && defined $accessor_for{$type};

	# A handful of GUC variables are shared between two parameters
	# (the same storage exposed under two names); emit the token once.
	next if $seen{$var}++;

	print $ofh "#ifdef $entry->{ifdef}\n" if $entry->{ifdef};
	printf $ofh "#define GUC_%s\t(%s)\n", $var, $var;
	print $ofh "#endif\n" if $entry->{ifdef};
}

print $ofh "\n#endif\t\t\t\t\t\t\t/* GUC_ACCESSORS_H */\n";

close $ofh;


sub print_boilerplate
{
	my ($fh, $fname) = @_;
	printf $fh <<EOM, $fname;
/*-------------------------------------------------------------------------
 *
 * %s
 *    Typed GUC read-accessor layer (threaded-runtime support)
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/utils/misc/gen_guc_accessors.pl
 *
 *-------------------------------------------------------------------------
 */
EOM

	return;
}
