#!/usr/bin/perl
#----------------------------------------------------------------------
#
# Generate guc_accessors.cocci from guc_parameters.dat.
#
# This emits the tree-wide Coccinelle semantic patch that rewrites every
# direct *read* of a GUC backing global into the typed accessor layer
# introduced by F3 (see docs/threading/F3_GUC_ACCESSORS.md and
# gen_guc_accessors.pl):
#
#     work_mem      ->  GetGUCInt(GUC_work_mem)
#     log_duration  ->  GetGUCBool(GUC_log_duration)
#     ...
#
# The patch is purely a *read* rewrite.  Coccinelle matches an identifier
# only in expression position, so declarations (`int work_mem = ...;`),
# externs (`extern int work_mem;`) and struct fields (`st->work_mem`) are
# left alone automatically.  The two contexts that ARE expression position
# but must NOT be rewritten -- an lvalue write (`work_mem = e`, `+=`, `++`,
# ...) and an address-of (`&work_mem`) -- are excluded explicitly via
# shared @lval@/@addr@/@addr2@ position rules; each per-variable rewrite
# rule then matches `position p != { lval.p, addr.p, addr2.p }`.
#
# A handful of address-of / lvalue residuals that the @addr@/@addr2@
# rules do not cover (e.g. `return &work_mem`, array initialisers) are
# rare and fixed by hand after applying the sweep.
#
# Storage-owning files (guc.c, guc_tables.c, guc_funcs.c, and the
# generated GUC tables) write the globals through the &variable pointers
# in the GUC table and must keep reading them directly; run-cocci.py's
# target-dir list plus a hand review keeps them out of the sweep.
#
# The generated .cocci is checked in (re-runnable via run-cocci.py).
# Regenerate it whenever guc_parameters.dat changes:
#
#     perl gen_guc_accessors_cocci.pl \
#         src/backend/utils/misc/guc_parameters.dat \
#         src/tools/cocci/guc_accessors.cocci
#
# Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
#
# src/backend/utils/misc/gen_guc_accessors_cocci.pl
#
#----------------------------------------------------------------------

use strict;
use warnings FATAL => 'all';

use FindBin;
use lib "$FindBin::RealBin/../../catalog";
use Catalog;

die "Usage: $0 INPUT_FILE OUTPUT_FILE\n" unless @ARGV == 2;
my ($input_fname, $output_fname) = @ARGV;

my $parse = Catalog::ParseData($input_fname);

# Map GUC type -> the typed accessor used to read it.
my %accessor_for = (
	bool => 'GetGUCBool',
	int => 'GetGUCInt',
	real => 'GetGUCReal',
	string => 'GetGUCString',
	enum => 'GetGUCEnum',);

# Collect the distinct backing-global names, in declaration order, with the
# accessor each one needs.  A few GUC variables are shared between two
# parameters (the same storage under two names); emit each global once.
my @vars;
my %seen;
foreach my $entry (@{$parse})
{
	my $type = $entry->{type} // '';
	my $var = $entry->{variable};

	next unless defined $var && defined $accessor_for{$type};
	next if $seen{$var}++;

	push @vars, { var => $var, accessor => $accessor_for{$type} };
}

# Alternation of every backing global, for the single read-match rule.
my $alternation = join('|', map { $_->{var} } @vars);

# Python dict literal mapping variable name -> typed accessor, for the
# script rule that selects the accessor per match.
my $py_map = join("\n", map { qq(    "$_->{var}": "$_->{accessor}",) } @vars);

open my $ofh, '>', $output_fname or die "could not open $output_fname: $!";

print $ofh <<EOM;
// guc_accessors.cocci -- tree-wide GUC read-accessor sweep.
//
// ******************************
// *** DO NOT EDIT THIS FILE! ***
// ******************************
//
// GENERATED by src/backend/utils/misc/gen_guc_accessors_cocci.pl from
// src/backend/utils/misc/guc_parameters.dat.  Regenerate after that file
// changes; do not hand-edit.  See docs/threading/F3_GUC_ACCESSORS.md.
//
// Rewrites a direct *read* of each GUC backing global into the typed
// accessor layer (utils/guc_accessors.h):
//
//     work_mem  ->  GetGUCInt(GUC_work_mem)
//
// DESIGN
// ------
// Coccinelle matches an identifier only in expression position, so
// declarations, externs and struct fields (st->work_mem) are left alone
// automatically.  The expression-position contexts that must NOT be
// rewritten are excluded as follows:
//   - an lvalue write (work_mem = e, +=, ++, ...) via the \@lval\@ rule;
//   - a member designator inside offsetof(T, work_mem) via the \@ofs\@ rule;
//   - an address-of (&work_mem) via a disjunction branch in the final
//     transformation rule (a bare `&g` is not a parseable standalone SmPL
//     rule body, so it cannot be a position-exclusion rule of its own).
// The read-match rule fires only at positions \@lval\@/\@ofs\@ did not bind;
// the final rule then skips the &g branch and rewrites the rest.
//
// Crucially ALL variables are matched in a SINGLE read rule (\@rd\@, via one
// big name alternation), and the per-variable accessor is chosen by a
// \@script:python\@ rule.  Doing it in one rule pass avoids a spatch gotcha:
// rules apply sequentially and recompute byte positions against the file as
// already modified by earlier rules, so a design with one rewrite rule per
// variable desyncs the shared lvalue/address-of positions the moment the
// first rewrite fires (later variables' write/addr sites then leak through).
// One pass keeps every position consistent -- and keeps the patch fast
// (constant rule count instead of ~1800 rules).
//
// A handful of address-of residuals not covered by \@addr\@/\@addr2\@ (e.g.
// array initialisers like `&Trace_locks`) are rare and fixed by hand after
// applying the sweep; the storage-owning files (guc.c, guc_tables.c,
// guc_funcs.c) keep reading the globals directly and are kept out of the
// sweep by review.
//
// Re-runnable via run-cocci.py (dry-run by default).

// Shared exclusion: a GUC global used as an lvalue (being written).
// Constraining these rules to the GUC name set (rather than any identifier)
// is essential for speed: it stops spatch from testing the disjunction at
// every identifier in the file (which is pathologically slow on large TUs).
\@lval\@ identifier g =~ "^($alternation)\$"; position p; expression e; \@\@
(
g\@p = e
|
g\@p += e
|
g\@p -= e
|
g\@p *= e
|
g\@p /= e
|
g\@p %= e
|
g\@p |= e
|
g\@p &= e
|
g\@p ^= e
|
g\@p <<= e
|
g\@p >>= e
|
g\@p++
|
g\@p--
)

// Shared exclusion: a struct field named like a GUC inside offsetof().  The
// second argument of offsetof is a member designator, not a read of the GUC
// global, so it must be left intact (e.g. offsetof(StdRdOptions, work_mem)).
\@ofs\@ identifier g =~ "^($alternation)\$"; position p; identifier T; \@\@
 offsetof(T, g\@p)

// Match a read of any GUC backing global, except at the excluded positions.
// Address-of (&g) is NOT excluded here: a bare `&g\@p` is not a parseable
// standalone SmPL rule body, so address-of is handled in the \@final\@
// transformation rule below via a disjunction branch instead.
\@rd\@ identifier g =~ "^($alternation)\$"; position p != { lval.p, ofs.p }; \@\@
g\@p

// Pick the typed accessor for the matched variable.
\@script:python rep\@ g << rd.g; acc; \@\@
m = {
$py_map
}
coccinelle.acc = m[g]

// Rewrite the read through the typed accessor and GUC_<variable> token.
//
// The disjunction leaves `&g` (address-of: passed by pointer, stored in the
// GUC table, used in array/struct initialisers, ...) untouched while
// rewriting every genuine read `g` -> acc(GUC_<g>).  Doing the address-of
// guard here (rather than as a separate \@addr\@ position rule) is what lets
// the patch stay idempotent: a bare `&g\@p` cannot be expressed as its own
// match rule, but inside a `( ... | ... )` disjunction it parses fine.
\@final\@ identifier rd.g; position rd.p; identifier rep.acc; fresh identifier tok = "GUC_" ## g; \@\@
(
 &g\@p
|
- g\@p
+ acc(tok)
)
EOM

close $ofh;
