#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/bark
#
# IDENTIFICATION
#    src/backend/access/bark/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/bark
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	bark.o \
	barkinsert.o \
	barkknn.o \
	barkscan.o \
	barksearch.o \
	barksort.o \
	barkutils.o \
	barkvalidate.o

include $(top_srcdir)/src/backend/common.mk
