#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/bark
#
# IDENTIFICATION
#    src/backend/access/bark/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/bark
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	bark.o

include $(top_srcdir)/src/backend/common.mk
