/*-------------------------------------------------------------------------
 *
 * parser_pushparse.c
 *	  Track B: drive PostgreSQL's SQL grammar with Lime's runtime push
 *	  parser over a ParserSnapshot, dispatching the base grammar's reduce
 *	  actions through the generated host-reduce wrapper (base_yyHostReduce,
 *	  emitted by `lime -n --host-reduce`).  This builds a real raw parse
 *	  tree in-process -- no subprocess, no C compiler.
 *
 * Isolated in its own translation unit because it includes Lime's
 * runtime headers via the <lime/...> path; that include directory is
 * confined here so the rest of the backend keeps PostgreSQL's own
 * headers (e.g. utils/snapshot.h, whose basename collides with Lime's).
 *
 * The composed ParserSnapshot (base grammar + any registered runtime
 * extensions) is supplied by parser_extension.c; this file only knows
 * how to feed the core scanner's token stream to a snapshot and recover
 * the resulting parse tree.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * src/backend/parser/parser_pushparse.c
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "gramparse.h"
#include "parser/parser.h"
#include "parser/parser_extension.h"
#include "parser/scanner.h"
#include "lib/stringinfo.h"
#include "utils/memutils.h"

#include <lime/lime_compiler.h>
#include <lime/parse_context.h>
#include <lime/snapshot.h>

/*
 * Generated by `lime -j -n --host-reduce` into gram_snapshot.c / gram.c.
 *   base_yyBuildSnapshot()  -- ParserSnapshot from the backend parser
 *                              tables, with snap->host_reduce wired to
 *                              base_yyHostReduce and the grammar source
 *                              embedded for in-process recomposition.
 *   base_yyHostReduce()     -- runs the static yy_rule_reduce_fn[ruleno]
 *                              with a stack yyParser whose yyscanner is
 *                              the host_reduce `user` pointer.
 */
extern ParserSnapshot * base_yyBuildSnapshot(void);
extern int	base_yyHostReduce(void *user, int ruleno,
							  const void *rhs_values, const int *rhs_locs,
							  int nrhs, void *lhs_out, int *lhs_loc_out);

/*
 * lime_snapshot_token_code (Lime v1.7.0) maps a token NAME to its
 * external code in a snapshot, or -1.  Declared in <lime/parser.h>, but
 * that header's include guard (PARSER_H) collides with PostgreSQL's
 * parser/parser.h, so we forward-declare it here.  The symbol lives in
 * liblime_parser.a.  (Reported to the Lime team: parser.h should use a
 * LIME_-prefixed guard.)
 */
extern int	lime_snapshot_token_code(const ParserSnapshot * snap,
									 const char *name);

extern bool raw_parser_lime_pushparse(core_yyscan_t yyscanner,
									  base_yy_extra_type *yyextra,
									  List **result);
extern bool raw_parser_lime_active(void);
extern bool pg_grammar_compose_install(unsigned int *base_nrule_out,
									   char **errmsg_out);

/*
 * Active parser snapshot.
 *
 *   base_snapshot     -- the base SQL grammar, built once per backend.
 *   composed_snapshot -- base + registered extension grammars, compiled
 *                        in-process; NULL until pg_grammar_compose_install
 *                        runs.  When set, parses use it instead of base.
 *   composed_base_nrule -- the base grammar's rule count; the host-reduce
 *                        dispatcher routes ruleno < this to the base
 *                        actions and ruleno >= this to extension rules.
 */
static ParserSnapshot * base_snapshot = NULL;
static ParserSnapshot * composed_snapshot = NULL;
static unsigned int composed_base_nrule = 0;

/*
 * raw_parser_lime_active
 *	  True once a composed grammar snapshot (base + registered
 *	  extensions) is installed -- i.e. at least one grammar extension
 *	  registered and pg_grammar_ext_prewarm()/lock composed it.  raw_parser
 *	  uses this to decide whether to drive the push parser.
 */
bool
raw_parser_lime_active(void)
{
	return composed_snapshot != NULL;
}

/*
 * pushparse_host_reduce
 *	  The composed snapshot's host-reduce dispatcher.  Routes a reduce by
 *	  composed rule number: base rules (ruleno < composed_base_nrule) run
 *	  the generated base actions via base_yyHostReduce; extension rules
 *	  (ruleno >= composed_base_nrule) route to their registered
 *	  PgGrammarReduceFn via pg_grammar_ext_resolve_reduce.  `user` is the
 *	  core scanner, threaded as the host_reduce user pointer.
 */
static int
pushparse_host_reduce(void *user, int ruleno,
					  const void *rhs_values, const int *rhs_locs,
					  int nrhs, void *lhs_out, int *lhs_loc_out)
{
	if ((unsigned int) ruleno < composed_base_nrule)
		return base_yyHostReduce(user, ruleno, rhs_values, rhs_locs,
								 nrhs, lhs_out, lhs_loc_out);

	return pg_grammar_ext_resolve_reduce((int) ((unsigned int) ruleno -
												composed_base_nrule),
										 user, nrhs,
										 (const void *const *) rhs_values,
										 rhs_locs, lhs_out);
}

static void pushparse_build_keyword_map(void);

/*
 * pg_grammar_compose_install
 *	  Merge the base grammar source with the registered extension
 *	  fragments, compile the result to a runtime ParserSnapshot
 *	  in-process (no subprocess, no C compiler), and install it as the
 *	  active composed snapshot.  Stores the base rule count in
 *	  *base_nrule_out.  Returns true on success; on failure sets
 *	  *errmsg_out to a palloc'd message and returns false.
 */
bool
pg_grammar_compose_install(unsigned int *base_nrule_out, char **errmsg_out)
{
	const char **frags;
	int			nfrags;
	StringInfoData merged;
	ParserSnapshot *snap = NULL;
	char	   *err = NULL;
	int			rc;
	int			nconflict = 0;

	if (base_snapshot == NULL)
	{
		base_snapshot = base_yyBuildSnapshot();
		if (base_snapshot == NULL)
		{
			if (errmsg_out)
				*errmsg_out = pstrdup("could not build base parser snapshot");
			return false;
		}
	}
	composed_base_nrule = base_snapshot->nrule;
	if (base_nrule_out)
		*base_nrule_out = composed_base_nrule;

	if (base_snapshot->grammar_source == NULL ||
		base_snapshot->grammar_source_len == 0)
	{
		if (errmsg_out)
			*errmsg_out = pstrdup("base snapshot has no embedded grammar "
								  "source; rebuild with lime -n");
		return false;
	}

	nfrags = pg_grammar_ext_pending_fragments(&frags);
	if (nfrags == 0)
		return true;			/* nothing to compose; base snapshot stands */

	/* base grammar text + each extension fragment, in registration order. */
	initStringInfo(&merged);
	appendBinaryStringInfo(&merged, base_snapshot->grammar_source,
						   (int) base_snapshot->grammar_source_len);
	for (int i = 0; i < nfrags; i++)
	{
		appendStringInfoChar(&merged, '\n');
		appendStringInfoString(&merged, frags[i]);
		appendStringInfoChar(&merged, '\n');
	}

	elog(DEBUG1, "composing grammar in-process for %d extension(s)", nfrags);
	rc = lime_compile_grammar_in_process_ex(merged.data, (size_t) merged.len,
											&snap, &err, &nconflict);
	pfree(merged.data);
	if (rc != 0 || snap == NULL)
	{
		if (errmsg_out)
			*errmsg_out = psprintf("in-process grammar compose failed: %s",
								   err ? err : "(no detail)");
		if (err)
			free(err);
		return false;
	}

	/*
	 * A nonzero conflict count means the compose succeeded only because the
	 * LALR table builder silently resolved >=1 shift/reduce (or keep-first
	 * reduce/reduce) conflict by table-build order, NOT by any extension
	 * author's intent.  In a multi-extension setting this is exactly the case
	 * where one loaded grammar shadows or mis-parses another (or base SQL):
	 * the resulting parser is well-formed but does not mean what the author
	 * wrote.  Refuse to install it rather than silently mis-parse; the
	 * extension author must remove the overlap.  (Lime v1.8.1
	 * lime_compile_grammar_in_process_ex surfaces this count; the plain entry
	 * point hid it.)
	 */
	if (nconflict > 0)
	{
		snapshot_release(snap);
		if (errmsg_out)
			*errmsg_out = psprintf("grammar extension compose introduced %d "
								   "unresolved conflict(s); a loaded grammar "
								   "extension shadows base SQL or another "
								   "extension. Refusing to install the composed "
								   "parser.", nconflict);
		if (err)
			free(err);
		return false;
	}
	if (err)
		free(err);

	/* Route base/extension reduces through the composed dispatcher. */
	snap->host_reduce = pushparse_host_reduce;
	composed_snapshot = snap;

	/* Build the scanner keyword map (lexeme -> composed token code). */
	pushparse_build_keyword_map();
	return true;
}

/*
 * Scanner keyword map: lexeme (lowercase source text) -> external token
 * code in the composed snapshot.  Built once after compose by resolving
 * each registered extension token's NAME via lime_snapshot_token_code.
 * scan.c consults it (through pg_grammar_ext_keyword_hook) so an
 * extension keyword lexeme resolves to its composed token code.
 *
 * `base_code` records, for a lexeme that ALSO matches a base SQL
 * keyword, that base keyword's token code.  Such colliding lexemes are
 * resolved at parse time by the admissibility oracle: at a parse state
 * where only the extension meaning fits (e.g. a QUEL verb at statement
 * start, where the base keyword cannot begin a statement) the scanner
 * emits the extension code; otherwise it keeps the base code.
 */
typedef struct PushparseKwEntry
{
	char	   *lexeme;			/* lowercase, NUL-terminated */
	int			code;			/* extension token code in composed snapshot */
	int			base_code;		/* base SQL token code, or -1 if no collision */
}			PushparseKwEntry;

static PushparseKwEntry * kw_map = NULL;
static int	kw_map_count = 0;
static int	kw_map_capacity = 0;

static void
pushparse_kw_add(const char *name, const char *lexeme,
				 PgGrammarExtKeywordCategory category, void *cb_arg)
{
	int			code;
	int			base_code = -1;
	int			kwnum;

	(void) category;
	(void) cb_arg;

	if (composed_snapshot == NULL)
		return;

	/* Resolve the token NAME to its external code in the composed snapshot. */
	code = lime_snapshot_token_code(composed_snapshot, name);
	if (code < 0)
		return;					/* token absent from composed grammar */

	/*
	 * Does this lexeme also match a base SQL keyword?  If so it is a
	 * collision: the scanner's base lookup would normally win, shadowing the
	 * extension.  Record the base token code so the push loop can ask the
	 * admissibility oracle which meaning fits the current parse state.
	 */
	kwnum = ScanKeywordLookup(lexeme, &ScanKeywords);
	if (kwnum >= 0)
		base_code = ScanKeywordTokens[kwnum];

	if (kw_map_count == kw_map_capacity)
	{
		int			newcap = kw_map_capacity ? kw_map_capacity * 2 : 8;

		if (kw_map == NULL)
			kw_map = MemoryContextAlloc(TopMemoryContext,
										sizeof(PushparseKwEntry) * newcap);
		else
			kw_map = repalloc(kw_map, sizeof(PushparseKwEntry) * newcap);
		kw_map_capacity = newcap;
	}
	kw_map[kw_map_count].lexeme = MemoryContextStrdup(TopMemoryContext, lexeme);
	kw_map[kw_map_count].code = code;
	kw_map[kw_map_count].base_code = base_code;
	kw_map_count++;
}

/*
 * pushparse_keyword_hook
 *	  Published to scan.c (pg_grammar_ext_keyword_hook).  Given a
 *	  lowercased identifier lexeme, return the extension token code if the
 *	  lexeme matches a registered extension keyword, else -1.  Linear scan
 *	  -- the registered-extension keyword set is small.
 */
static int
pushparse_keyword_hook(const char *lower_lexeme)
{
	for (int i = 0; i < kw_map_count; i++)
	{
		if (strcmp(kw_map[i].lexeme, lower_lexeme) == 0)
			return kw_map[i].code;
	}
	return -1;
}

static void
pushparse_build_keyword_map(void)
{
	kw_map_count = 0;			/* rebuilt fresh each compose */
	pg_grammar_ext_foreach_token(pushparse_kw_add, NULL);
	if (kw_map_count > 0)
		pg_grammar_ext_keyword_hook = pushparse_keyword_hook;
	elog(DEBUG1, "grammar extension keyword map: %d entries published",
		 kw_map_count);
}

/*
 * pushparse_resolve_collision
 *	  For a token `tok` the scanner produced as a BASE SQL keyword, check
 *	  whether a loaded extension also claims that lexeme (a collision) and,
 *	  if so, decide which token the parser should actually receive in its
 *	  current state:
 *
 *	    - only the extension token is admissible -> the extension code
 *	      (e.g. a QUEL verb at statement start, where the base keyword
 *	      cannot begin a statement);
 *	    - only the base token is admissible -> the base code (unchanged);
 *	    - both admissible -> a genuine ambiguity (e.g. DELETE: base
 *	      `DELETE FROM ...` vs QUEL `delete e where ...`).  The two diverge
 *	      one token later, so *need_peek is set and the caller peeks the
 *	      next token to decide between *peek_base_code and *peek_ext_code;
 *	    - neither admissible -> keep the base code and let the base grammar
 *	      produce the error.
 *
 *	  Non-colliding tokens return `tok` unchanged with zero oracle calls
 *	  and *need_peek = false.
 */
static int
pushparse_resolve_collision(ParseContext * ctx, int tok,
							bool *need_peek,
							int *peek_base_code, int *peek_ext_code)
{
	*need_peek = false;

	for (int i = 0; i < kw_map_count; i++)
	{
		LimeTokenAdmissibility ad_base;
		LimeTokenAdmissibility ad_ext;

		if (kw_map[i].base_code != tok)
			continue;			/* not a collision on this base code */

		ad_base = parse_context_token_admissible(ctx, kw_map[i].base_code);
		ad_ext = parse_context_token_admissible(ctx, kw_map[i].code);

		if (ad_ext != LIME_TOK_NONE && ad_base == LIME_TOK_NONE)
			return kw_map[i].code;	/* only the extension fits here */

		if (ad_ext != LIME_TOK_NONE && ad_base != LIME_TOK_NONE)
		{
			/* Genuine ambiguity: resolve with one token of lookahead. */
			*need_peek = true;
			*peek_base_code = kw_map[i].base_code;
			*peek_ext_code = kw_map[i].code;
			return tok;
		}

		/* Only base (or neither) admissible: keep the base meaning. */
		return tok;
	}
	return tok;
}

/*
 * pushparse_resolve_ext_keyword
 *	  An extension keyword (one whose lexeme the scanner mapped to an
 *	  extension token code via pushparse_keyword_hook) is, like a base
 *	  unreserved keyword, usable as an ordinary identifier in contexts that
 *	  expect a name (e.g. `CREATE EXTENSION upsert`, a column named
 *	  "upsert").  The scanner cannot know the parse state, so it always
 *	  emits the keyword code; here we consult the admissibility oracle: if
 *	  the keyword token does not fit the current LR state but IDENT does,
 *	  rewrite it to IDENT so the lexeme behaves as a name.  Tokens that are
 *	  not extension keywords, or that ARE admissible as the keyword, pass
 *	  through unchanged.
 */
static int
pushparse_resolve_ext_keyword(ParseContext * ctx, int tok)
{
	for (int i = 0; i < kw_map_count; i++)
	{
		if (kw_map[i].code != tok)
			continue;			/* not an extension keyword code */

		if (parse_context_token_admissible(ctx, tok) == LIME_TOK_NONE &&
			parse_context_token_admissible(ctx, IDENT) != LIME_TOK_NONE)
			return IDENT;		/* usable here only as a name */
		return tok;
	}
	return tok;
}

/*
 * pushparse_peek_resolves_ext
 *	  One-token lookahead disambiguation for a both-admissible collision.
 *	  `next` is the token that follows the colliding keyword.  Returns true
 *	  if the EXTENSION meaning wins.
 *
 *	  For DELETE -- the only verb that legitimately leads a statement in
 *	  both grammars -- base `DELETE` is always followed by FROM, while QUEL
 *	  `delete e where ...` is followed by the relation-variable identifier.
 *	  So the discriminator is exactly one token: next == FROM means base
 *	  SQL DELETE; anything else means the extension.  This is the
 *	  divergence point MULTI_GRAMMAR.md identifies for the delete case.
 *
 *	  Keeping base on next == FROM guarantees base SQL DELETE is never
 *	  stolen; the extension only wins where base DELETE cannot continue.
 *
 * ponytail: one-token peek, sufficient because every current both-admissible
 * collision (only DELETE today) diverges at the very next token.  If a future
 * grammar extension introduces a both-admissible verb whose dialects diverge
 * DEEPER inside the statement (e.g. SQL LIMIT vs an Oracle-style ROWNUM tail),
 * one token is not enough: upgrade this to Lime's Tier-1 full-statement
 * fork-resolve -- buffer the rest of the statement and run lime_simulate_parse
 * (lime/parse_context.h) / lime_mg_resolve (lime/multi_grammar.h) over the
 * candidate token streams, preferring the one that reaches accept.  Not done
 * now: it would require buffering the whole statement (breaking the
 * interleaved scan/parse/oracle loop the keyword-vs-keyword and
 * keyword-vs-identifier paths depend on) to replace code that is already
 * correct for the only collision that exists.
 */
static bool
pushparse_peek_resolves_ext(int next)
{
	return (next != FROM);
}

/*
 * pushparse_ascii_to_named
 *	  Translate a raw single-character token code (the ASCII byte the core
 *	  scanner emits for ';' '(' ',' '+' ...) to the backend grammar's named
 *	  token id (SEMI, LPAREN, COMMA, PLUS, ...).  The pull parser does this
 *	  inside base_yyparse (gram.lime's ascii_to_lime_token); the push path
 *	  must apply the same mapping before parse_token, or single-character
 *	  tokens arrive at the wrong external code and are rejected.  Named
 *	  tokens (keywords, IDENT, ICONST, ...) pass through unchanged.
 *
 *	  Kept in sync with gram.lime's ascii_to_lime_token; the named codes
 *	  come from gram.h (via gramparse.h).
 */
static inline int
pushparse_ascii_to_named(int t)
{
	switch (t)
	{
		case '(':
			return LPAREN;
		case ')':
			return RPAREN;
		case '[':
			return LBRACKET;
		case ']':
			return RBRACKET;
		case ',':
			return COMMA;
		case ';':
			return SEMI;
		case ':':
			return COLON;
		case '.':
			return DOT;
		case '+':
			return PLUS;
		case '-':
			return MINUS;
		case '*':
			return STAR;
		case '/':
			return SLASH;
		case '%':
			return PERCENT;
		case '^':
			return CARET;
		case '|':
			return PIPE;
		case '<':
			return LT;
		case '>':
			return GT;
		case '=':
			return EQ;
		default:
			return t;
	}
}

/*
 * raw_parser_lime_pushparse
 *	  Parse `str` by driving the Lime push parser over the (base or
 *	  composed) ParserSnapshot.  On success stores the parse-tree List in
 *	  *result and returns true; on a syntax error returns false with
 *	  *result = NIL (matching base_yyparse's NIL-on-error contract).
 *
 * The caller (raw_parser) owns scanner setup/teardown and lookahead-mode
 * initialization, exactly as for the pull-parser path.
 */
bool
raw_parser_lime_pushparse(core_yyscan_t yyscanner,
						  base_yy_extra_type *yyextra,
						  List **result)
{
	ParserSnapshot *snap;
	ParseContext *ctx;
	int			rc = 0;
	bool		accepted = false;
	void	   *tree = NULL;
	YYLTYPE		error_lloc = 0;

	/* One-token pushback buffer for colliding-keyword (DELETE) lookahead. */
	bool		have_buffered = false;
	int			buffered_tok = 0;
	YYSTYPE		buffered_lval;
	YYLTYPE		buffered_lloc = 0;

	*result = NIL;

	/*
	 * Use the composed snapshot (base + extensions) when grammar extensions
	 * have been installed; otherwise the base grammar.  Both carry a
	 * host_reduce hook that runs base actions; the composed snapshot's hook
	 * (pushparse_host_reduce) additionally routes extension-rule reduces.
	 */
	if (composed_snapshot != NULL)
		snap = composed_snapshot;
	else
	{
		if (base_snapshot == NULL)
		{
			base_snapshot = base_yyBuildSnapshot();
			if (base_snapshot == NULL)
				elog(ERROR, "could not build base parser snapshot");
		}
		snap = base_snapshot;
	}

	/*
	 * Borrow the snapshot: it lives for the backend's lifetime, far longer
	 * than this parse, so we skip the per-parse refcount atomics.
	 */
	ctx = parse_begin_borrowed(snap);
	if (ctx == NULL)
		elog(ERROR, "could not begin parse");

	/*
	 * Route reduces, passing the live scanner so %extra_argument (yyscanner)
	 * is available to every action.  The composed snapshot already wires
	 * pushparse_host_reduce as its host_reduce; for the base snapshot we
	 * install base_yyHostReduce explicitly (it dispatches base rules only,
	 * which is all the base grammar has).
	 */
	if (composed_snapshot != NULL)
		parse_set_host_reduce(ctx, pushparse_host_reduce, yyscanner);
	else
		parse_set_host_reduce(ctx, base_yyHostReduce, yyscanner);

	for (;;)
	{
		YYSTYPE		lval;
		YYLTYPE		lloc = 0;
		int			tok;
		void	   *boxed;

		if (have_buffered)
		{
			/* Replay a token peeked during collision resolution. */
			tok = buffered_tok;
			lval = buffered_lval;
			lloc = buffered_lloc;
			have_buffered = false;
		}
		else
		{
			tok = base_yylex(&lval, &lloc, yyscanner);
			tok = pushparse_ascii_to_named(tok);
		}

		/*
		 * Colliding-keyword resolution (composed snapshot only): if the
		 * scanner produced a base SQL keyword that a loaded extension also
		 * claims, ask the admissibility oracle which meaning fits the current
		 * parse state.  No-op for non-colliding tokens.  This runs for both
		 * freshly-lexed and replayed-from-buffer tokens: a token peeked to
		 * disambiguate an earlier collision may itself be a colliding keyword
		 * (e.g. `range of ...` -- `range` peeks `of`, and `of` must still
		 * resolve to K_QUEL_OF, not base OF).
		 */
		if (composed_snapshot != NULL)
		{
			bool		need_peek = false;
			int			base_code = 0;
			int			ext_code = 0;

			tok = pushparse_resolve_collision(ctx, tok, &need_peek,
											  &base_code, &ext_code);
			if (need_peek)
			{
				/*
				 * Genuine ambiguity (DELETE): peek the next token, buffer it
				 * to feed after this one, and choose the base or extension
				 * meaning from one token of lookahead.
				 */
				buffered_tok = base_yylex(&buffered_lval,
										  &buffered_lloc, yyscanner);
				buffered_tok = pushparse_ascii_to_named(buffered_tok);
				have_buffered = true;

				if (pushparse_peek_resolves_ext(buffered_tok))
					tok = ext_code;
				else
					tok = base_code;
			}

			/*
			 * An extension keyword that does not collide with a base SQL
			 * keyword still must yield to IDENT where the grammar expects a
			 * name (e.g. `CREATE EXTENSION upsert`).  Tier-0 publishing made
			 * the scanner emit the keyword code unconditionally; fall back to
			 * IDENT where the keyword token is inadmissible.
			 */
			if (!need_peek)
				tok = pushparse_resolve_ext_keyword(ctx, tok);
		}

		/*
		 * PostgreSQL's YYSTYPE is a union of pointer-width members.  The push
		 * parser stores one pointer-width payload per token and hands it to
		 * the base action as the matching $N; box the union's pointer
		 * payload.
		 */
		memcpy(&boxed, &lval, sizeof(void *));

		rc = parse_token(ctx, tok, boxed, lloc);

		if (tok == 0)
		{
			/*
			 * EOF.  parse_token returns 1 ("EOF accepts") on a successful
			 * parse and a different non-zero / zero on failure; treat accept
			 * (rc == 1) as success, everything else as error.
			 */
			accepted = (rc == 1);
			if (!accepted)
				error_lloc = lloc;
			break;
		}
		if (rc != 0)			/* mid-stream syntax error */
		{
			accepted = false;
			error_lloc = lloc;
			break;
		}
	}

	if (accepted)
	{
		tree = parse_result(ctx);
		/* The start-rule action assigns yyextra->parsetree; prefer it. */
		*result = yyextra->parsetree;
		(void) tree;
	}

	parse_end(ctx);

	if (!accepted)
	{
		/*
		 * Raise the standard syntax error the pull parser would emit via
		 * base_yyerror().  scanner_yyerror() reads the scanner's current
		 * token location and ereport()s "syntax error at or near ..."; it
		 * does not return.  Without this the push path would silently treat
		 * an unparsable statement (e.g. a bare identifier) as an empty parse,
		 * diverging from the base parser.
		 */
		(void) error_lloc;
		scanner_yyerror("syntax error", yyscanner);
	}

	return accepted;
}
