#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lib (miscellaneous stuff)
#
# IDENTIFICATION
#    src/backend/lib/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/lib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	bipartite_match.o \
	bloomfilter.o \
	chimp.o \
	dshash.o \
	float16.o \
	hyperloglog.o \
	ilist.o \
	integerset.o \
	knapsack.o \
	pairingheap.o \
	rbtree.o \
	simple8b.o \

include $(top_srcdir)/src/backend/common.mk
