# Copyright (c) 2021-2026, PostgreSQL Global Development Group

"""Port of src/test/subscription/t/008_diff_schema.pl.

Behavior with a different schema on the subscriber (extra columns with local
defaults, replica-identity column added after the fact, missing columns).
"""


def test_diff_schema(create_pg):
    """Subscriber keeps local defaults for extra columns; errors on missing ones."""
    publisher = create_pg("publisher", allows_streaming="logical")
    subscriber = create_pg("subscriber")

    publisher.safe_psql("CREATE TABLE test_tab (a int primary key, b varchar)")
    publisher.safe_psql("INSERT INTO test_tab VALUES (1, 'foo'), (2, 'bar')")

    subscriber.safe_psql(
        "CREATE TABLE test_tab (a int primary key, b text, "
        "c timestamptz DEFAULT now(), d bigint DEFAULT 999, "
        "e int GENERATED BY DEFAULT AS IDENTITY)"
    )

    connstr = publisher.connstr() + " dbname=postgres"
    publisher.safe_psql("CREATE PUBLICATION tap_pub FOR ALL TABLES")
    subscriber.safe_psql(
        "CREATE SUBSCRIPTION tap_sub CONNECTION '{}' PUBLICATION tap_pub".format(
            connstr
        )
    )

    subscriber.wait_for_subscription_sync(publisher, "tap_sub")

    assert (
        subscriber.safe_psql("SELECT count(*), count(c), count(d = 999) FROM test_tab")
        == "2|2|2"
    ), "check initial data was copied to subscriber"

    publisher.safe_psql("UPDATE test_tab SET b = encode(sha256(b::bytea), 'hex')")
    publisher.wait_for_catchup("tap_sub")
    assert (
        subscriber.safe_psql(
            "SELECT count(*), count(c), count(d = 999), count(e) FROM test_tab"
        )
        == "2|2|2|2"
    ), "check extra columns contain local defaults after copy"

    subscriber.safe_psql(
        "UPDATE test_tab SET c = 'epoch'::timestamptz + 987654321 * interval '1s'"
    )
    publisher.safe_psql("UPDATE test_tab SET b = encode(sha256(a::text::bytea), 'hex')")
    publisher.wait_for_catchup("tap_sub")
    assert (
        subscriber.safe_psql(
            "SELECT count(*), count(extract(epoch from c) = 987654321), "
            "count(d = 999) FROM test_tab"
        )
        == "2|2|2"
    ), "check extra columns contain locally changed data"

    publisher.safe_psql("INSERT INTO test_tab VALUES (3, 'baz')")
    publisher.wait_for_catchup("tap_sub")
    assert (
        subscriber.safe_psql(
            "SELECT count(*), count(c), count(d = 999), count(e) FROM test_tab"
        )
        == "3|3|3|3"
    ), "check extra columns contain local defaults after apply"

    # Replica-identity column added on the subscriber not yet on the publisher.
    publisher.safe_psql("CREATE TABLE test_tab2 (a int)")
    subscriber.safe_psql("CREATE TABLE test_tab2 (a int)")
    subscriber.safe_psql("ALTER SUBSCRIPTION tap_sub REFRESH PUBLICATION")
    subscriber.wait_for_subscription_sync()

    subscriber.safe_psql("ALTER TABLE test_tab2 ADD COLUMN b serial PRIMARY KEY")
    publisher.safe_psql("INSERT INTO test_tab2 VALUES (1)")
    publisher.wait_for_catchup("tap_sub")
    assert (
        subscriber.safe_psql("SELECT count(*), min(a), max(a) FROM test_tab2")
        == "1|1|1"
    ), "check replicated inserts on subscriber"

    # Missing columns on the subscriber should report an error.
    publisher.safe_psql("CREATE TABLE test_tab3 (a int, b int, c int)")
    subscriber.safe_psql("CREATE TABLE test_tab3 (a int)")
    offset = subscriber.current_log_position()
    subscriber.safe_psql("ALTER SUBSCRIPTION tap_sub REFRESH PUBLICATION")
    subscriber.wait_for_log(
        r"ERROR: ( [A-Z0-9]+:)? logical replication target relation "
        r'"public.test_tab3" is missing replicated columns: "b", "c"',
        offset,
    )

    subscriber.stop()
    publisher.stop()
