# Copyright (c) 2022-2026, PostgreSQL Global Development Group

backend_sources += files(
  'orvos_attitem.c',
  'orvos_attpage.c',
  'orvos_btree.c',
  'orvos_compression.c',
  'orvos_freepagemap.c',
  'orvos_inspect.c',
  'orvos_meta.c',
  'orvos_overflow.c',
  'orvos_planner.c',
  'orvos_simple8b.c',
  'orvos_tiditem.c',
  'orvos_tidpage.c',
  'orvos_tupslot.c',
  'orvos_undolog.c',
  'orvos_undorec.c',
  'orvos_visibility.c',
  'orvos_wal.c',
  'orvos_handler.c',
  'orvos_stats.c',
)
