# Copyright (c) 2025, PostgreSQL Global Development Group

from ._env import (
    require_test_extras,
    skip_unless_test_extras,
    test_timeout_default,
)
from .command import CommandResult, PgBin, ProgramResult
from .errors import (
    PgError,
    PgServerError,
    PgSqlError,
    LibpqError,
    QueryCanceled,
    UniqueViolation,
    ForeignKeyViolation,
    CheckViolation,
    NotNullViolation,
    InsufficientPrivilege,
    UndefinedTable,
    UndefinedColumn,
    SerializationFailure,
    DeadlockDetected,
    AdminShutdown,
    CrashShutdown,
    CannotConnectNow,
)
from .fake import faker, meaningful_text, rand_str
from .modes import CatchupMode, SlotCatchupMode, StopMode
from .kerberos import KerberosServer
from .server import PostgresServer
from .sqlresult import SqlResult
from .util import (
    wait_for_file,
    wait_until,
    compare_files,
    check_pg_config,
    scan_server_header,
    append_to_file,
    check_mode_recursive,
    chmod_recursive,
    get_free_port,
    slurp_dir,
    slurp_file,
)

__all__ = [
    "require_test_extras",
    "skip_unless_test_extras",
    "test_timeout_default",
    "faker",
    "meaningful_text",
    "rand_str",
    "KerberosServer",
    "PostgresServer",
    "SqlResult",
    "StopMode",
    "CatchupMode",
    "SlotCatchupMode",
    "PgBin",
    "CommandResult",
    "ProgramResult",
    "PgError",
    "PgServerError",
    "PgSqlError",
    "LibpqError",
    "QueryCanceled",
    "UniqueViolation",
    "ForeignKeyViolation",
    "CheckViolation",
    "NotNullViolation",
    "InsufficientPrivilege",
    "UndefinedTable",
    "UndefinedColumn",
    "SerializationFailure",
    "DeadlockDetected",
    "AdminShutdown",
    "CrashShutdown",
    "CannotConnectNow",
    "append_to_file",
    "check_mode_recursive",
    "chmod_recursive",
    "get_free_port",
    "slurp_file",
    "slurp_dir",
    "check_pg_config",
    "scan_server_header",
    "compare_files",
    "wait_for_file",
    "wait_until",
]
