/*-------------------------------------------------------------------------
 *
 * bootscanner.c
 *	  Parser driver for PostgreSQL bootstrap (BKI) input.
 *
 * The lexical scanner moved to bootscanner.lex (Lime v0.2.1's lexer
 * subsystem).  This file is now a thin shim: it slurps stdin into a
 * StringInfo, calls BootLexFeedBytes once, and dispatches the
 * generated lexer's emit callbacks into Lime's push parser
 * (boot_yyAlloc / boot_yyLoc / boot_yyFree).  Replaces the former
 * 502-line hand-rolled state machine.
 *
 * Token-side responsibility: the .lex file maps matched text to a
 * parser token code via LEX_EMIT(...).  This file's emit callback
 * sets yylval (kw or str member) before pushing to the parser.
 *
 * Public interface, matching include/bootstrap/bootstrap.h:
 *
 *	int  boot_yyparse(yyscan_t yyscanner);
 *	int  boot_yylex_init(yyscan_t *yyscannerp);
 *	void boot_yyerror(yyscan_t yyscanner, const char *message);
 *
 * boot_yylex no longer exists -- the parser is fed by the driver
 * loop directly, not by a yylex() pull callback.  Same observable
 * behavior; identical token stream byte-for-byte against the
 * pre-flip bison+flex pair.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/backend/bootstrap/bootscanner.c
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include <stdio.h>
#include <unistd.h>

#include "bootstrap/bootstrap.h"
#include "lib/stringinfo.h"
#include "miscadmin.h"
#include "utils/memutils.h"

#include "bootparse.h"
#include "boot_gram_yytype.h"

/*
 * Generated by `lime -X bootscanner.lex` (see meson.build).  Provides
 * the BootLexer push API and the BOOT_LEX_OK / BOOT_LEX_ERROR result
 * codes.
 */
#include "bootscanner_lex.h"

/* DeescapeQuotedString is exported from guc-file.c. */
extern char *DeescapeQuotedString(const char *s);

/* Lime-generated push parser entry points (%name boot_yy). */
extern void *boot_yyAlloc(void *(*mallocProc) (size_t));
extern void boot_yyFree(void *p, void (*freeProc) (void *));
extern void boot_yy(void *yyp, int yymajor, YYSTYPE yyminor,
					yyscan_t yyscanner);

/*
 * Per-line working context and column-read counter.  Referenced from
 * the Lime-generated grammar actions in bootparse.lime; defined here
 * (matching the retired bootparse.y file-static variables).
 */
MemoryContext boot_per_line_ctx = NULL;
int			boot_num_columns_read = 0;

/* ------------------------------------------------------------------------- */
/* Scanner state                                                             */
/* ------------------------------------------------------------------------- */

typedef struct BootYyScanner
{
	StringInfoData buf;			/* full input slurped from stdin */
	int			yylineno;		/* tracked for boot_yyerror messages */
	void	   *parser;			/* boot_yyAlloc handle */
	bool		error_seen;		/* set by emit callback on LEX_ERROR */
} BootYyScanner;

/* ------------------------------------------------------------------------- */
/* Hooks called from bootparse.lime actions                                  */
/* ------------------------------------------------------------------------- */

void
boot_do_start(void)
{
	Assert(CurrentMemoryContext == CurTransactionContext);
	if (boot_per_line_ctx == NULL)
		boot_per_line_ctx = AllocSetContextCreate(CurTransactionContext,
												  "bootstrap per-line processing",
												  ALLOCSET_DEFAULT_SIZES);
	MemoryContextSwitchTo(boot_per_line_ctx);
}

void
boot_do_end(void)
{
	MemoryContextSwitchTo(CurTransactionContext);
	MemoryContextReset(boot_per_line_ctx);
	CHECK_FOR_INTERRUPTS();
	if (isatty(0))
	{
		printf("bootstrap> ");
		fflush(stdout);
	}
}

/* ------------------------------------------------------------------------- */
/* Scanner public interface                                                  */
/* ------------------------------------------------------------------------- */

int
boot_yylex_init(yyscan_t *yyscannerp)
{
	BootYyScanner *s = palloc0_object(BootYyScanner);

	initStringInfo(&s->buf);
	s->yylineno = 1;

	*yyscannerp = (yyscan_t) s;
	return 0;
}

/* ------------------------------------------------------------------------- */
/* Emit callback: lexer -> parser bridge                                     */
/* ------------------------------------------------------------------------- */

/*
 * Called by BootLexFeedBytes for each matched rule.  rule_id is the
 * value from LEX_EMIT(...) in bootscanner.lex -- which we set to the
 * parser-side token code (OPEN, ID, COMMA, ...).  text/len point into
 * the input buffer (no NUL terminator).
 *
 * Translates (rule_id, text, len) into (yylval, token) and pushes via
 * boot_yy to the Lime parser.
 */
static void
boot_emit_cb(void *user, int token, const char *text, size_t len)
{
	BootYyScanner *s = user;
	YYSTYPE		yylval;

	memset(&yylval, 0, sizeof(yylval));

	switch (token)
	{
			case ID:
			{
				char	   *literal = palloc(len + 1);

							memcpy(literal, text, len);
							literal[len] = '\0';
				if			(len >= 2 && text[0] == '\'')
				{
					/* Quoted-string ID: deescape per the flex behavior. */
					yylval.str = DeescapeQuotedString(literal);
				}
				else
				{
					/* Unquoted identifier: pstrdup of the matched text. */
					yylval.str = literal;
				}
							break;
			}

			case		OPEN:
			case		XCLOSE:
			case		XCREATE:
			case		OBJ_ID:
			case		XBOOTSTRAP:
			case		XSHARED_RELATION:
			case		XROWTYPE_OID:
			case		INSERT_TUPLE:
			case		XDECLARE:
			case		XBUILD:
			case		INDICES:
			case		UNIQUE:
			case		INDEX:
			case		ON:
			case		USING:
			case		XTOAST:
			case		XFORCE:
			case		XNOT:
			case		XNULL:
			{
				/*
				 * Keyword tokens carry the keyword text.  The flex original
				 * pointed yylval->kw at the static keyword string; we pstrdup
				 * the matched span instead, which is harmless (the grammar
				 * only reads it during error reporting and the per-line
				 * context resets after each statement).
				 */
				char	   *kw = palloc(len + 1);

							memcpy(kw, text, len);
							kw[len] = '\0';
							yylval.kw = kw;
							break;
			}

			case		NULLVAL:
			case		COMMA:
			case		EQUALS:
			case		LPAREN:
			case		RPAREN:
			/* No semantic value. */
						break;

		default:
			/* Should not happen given the rules in bootscanner.lex. */
			elog(ERROR,
				 "bootscanner: unexpected token code %d for span \"%.*s\"",
				 token, (int) len, text);
	}

	boot_yy(s->parser, token, yylval, (yyscan_t) s);
}

/* ------------------------------------------------------------------------- */
/* Error reporting                                                           */
/* ------------------------------------------------------------------------- */

pg_noreturn void
boot_yyerror(yyscan_t yyscanner, const char *message)
{
	BootYyScanner *s = (BootYyScanner *) yyscanner;

	ereport(ERROR,
			(errcode(ERRCODE_SYNTAX_ERROR),
			 errmsg_internal("%s at line %d", message, s->yylineno)));
}

/* ------------------------------------------------------------------------- */
/* Parser driver                                                             */
/* ------------------------------------------------------------------------- */

/*
 * Slurp stdin into the scanner's StringInfo, count newlines for error
 * messages, then drive the Lime lexer over the buffer once.  EOF is
 * signalled to the parser via boot_yy(parser, 0, ...).
 */
int
boot_yyparse(yyscan_t yyscanner)
{
	BootYyScanner *s = (BootYyScanner *) yyscanner;
	BootLexer  *lex;
	YYSTYPE		zero_yylval;
	int			c;

	/* Read all of stdin. */
	while ((c = fgetc(stdin)) != EOF)
	{
		appendStringInfoChar(&s->buf, (char) c);
		if (c == '\n')
			s->yylineno++;
	}

	s->parser = boot_yyAlloc(palloc);

	lex = BootLexAlloc(palloc);
	if (lex == NULL)
	{
		boot_yyFree(s->parser, pfree);
		ereport(ERROR,
				(errcode(ERRCODE_OUT_OF_MEMORY),
				 errmsg_internal("BootLexAlloc returned NULL")));
	}

	/*
	 * Feed the entire buffer in one call.  Lime's lexer can suspend mid-token
	 * across feeds (post-v0.2.1), but bootstrap is small enough that
	 * single-shot is simpler.  BootLexFeedEOF emits any final <<EOF>> rule
	 * (we have none).
	 */
	if (BootLexFeedBytes(lex, s->buf.data, s->buf.len,
						 boot_emit_cb, s) != BOOT_LEX_OK)
	{
		BootLexFree(lex, pfree);
		boot_yyFree(s->parser, pfree);
		ereport(ERROR,
				(errcode(ERRCODE_SYNTAX_ERROR),
				 errmsg_internal("bootstrap scanner error at line %d",
								 s->yylineno)));
	}
	BootLexFeedEOF(lex, boot_emit_cb, s);
	BootLexFree(lex, pfree);

	/* Signal end of input to the parser. */
	memset(&zero_yylval, 0, sizeof(zero_yylval));
	boot_yy(s->parser, 0, zero_yylval, yyscanner);

	boot_yyFree(s->parser, pfree);
	return 0;
}
