/*-------------------------------------------------------------------------
 *
 * pg_propgraph_label_d.h
 *    Macro definitions for pg_propgraph_label
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROPGRAPH_LABEL_D_H
#define PG_PROPGRAPH_LABEL_D_H

/* Macros related to the structure of pg_propgraph_label */

#define PropgraphLabelRelationId 6470
#define PropgraphLabelObjectIndexId 6471
#define PropgraphLabelGraphNameIndexId 6478

#define Anum_pg_propgraph_label_oid 1
#define Anum_pg_propgraph_label_pglpgid 2
#define Anum_pg_propgraph_label_pgllabel 3

#define Natts_pg_propgraph_label 3

/* Definitions copied from pg_propgraph_label.h */


/* OID symbols for objects defined in pg_propgraph_label.dat */


#endif							/* PG_PROPGRAPH_LABEL_D_H */
