/*-------------------------------------------------------------------------
 *
 * pg_propgraph_element_d.h
 *    Macro definitions for pg_propgraph_element
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROPGRAPH_ELEMENT_D_H
#define PG_PROPGRAPH_ELEMENT_D_H

/* Macros related to the structure of pg_propgraph_element */

#define PropgraphElementRelationId 6466
#define PropgraphElementObjectIndexId 6467
#define PropgraphElementAliasIndexId 6468

#define Anum_pg_propgraph_element_oid 1
#define Anum_pg_propgraph_element_pgepgid 2
#define Anum_pg_propgraph_element_pgerelid 3
#define Anum_pg_propgraph_element_pgealias 4
#define Anum_pg_propgraph_element_pgekind 5
#define Anum_pg_propgraph_element_pgesrcvertexid 6
#define Anum_pg_propgraph_element_pgedestvertexid 7
#define Anum_pg_propgraph_element_pgekey 8
#define Anum_pg_propgraph_element_pgesrckey 9
#define Anum_pg_propgraph_element_pgesrcref 10
#define Anum_pg_propgraph_element_pgesrceqop 11
#define Anum_pg_propgraph_element_pgedestkey 12
#define Anum_pg_propgraph_element_pgedestref 13
#define Anum_pg_propgraph_element_pgedesteqop 14

#define Natts_pg_propgraph_element 14

/* Definitions copied from pg_propgraph_element.h */


/*
 * Symbolic values for pgekind column
 */
#define PGEKIND_VERTEX 'v'
#define PGEKIND_EDGE 'e'


/* OID symbols for objects defined in pg_propgraph_element.dat */


#endif							/* PG_PROPGRAPH_ELEMENT_D_H */
