/*-------------------------------------------------------------------------
 *
 * pg_propgraph_property_d.h
 *    Macro definitions for pg_propgraph_property
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROPGRAPH_PROPERTY_D_H
#define PG_PROPGRAPH_PROPERTY_D_H

/* Macros related to the structure of pg_propgraph_property */

#define PropgraphPropertyRelationId 6473
#define PropgraphPropertyObjectIndexId 6474
#define PropgraphPropertyNameIndexId 6475

#define Anum_pg_propgraph_property_oid 1
#define Anum_pg_propgraph_property_pgppgid 2
#define Anum_pg_propgraph_property_pgpname 3
#define Anum_pg_propgraph_property_pgptypid 4
#define Anum_pg_propgraph_property_pgptypmod 5
#define Anum_pg_propgraph_property_pgpcollation 6

#define Natts_pg_propgraph_property 6

/* Definitions copied from pg_propgraph_property.h */


/* OID symbols for objects defined in pg_propgraph_property.dat */


#endif							/* PG_PROPGRAPH_PROPERTY_D_H */
