/*-------------------------------------------------------------------------
 *
 * pg_propgraph_label_property_d.h
 *    Macro definitions for pg_propgraph_label_property
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROPGRAPH_LABEL_PROPERTY_D_H
#define PG_PROPGRAPH_LABEL_PROPERTY_D_H

/* Macros related to the structure of pg_propgraph_label_property */

#define PropgraphLabelPropertyRelationId 6482
#define PropgraphLabelPropertyObjectIndexId 6492
#define PropgraphLabelPropertyLabelPropIndexId 6493

#define Anum_pg_propgraph_label_property_oid 1
#define Anum_pg_propgraph_label_property_plppropid 2
#define Anum_pg_propgraph_label_property_plpellabelid 3
#define Anum_pg_propgraph_label_property_plpexpr 4

#define Natts_pg_propgraph_label_property 4

/* Definitions copied from pg_propgraph_label_property.h */


/* OID symbols for objects defined in pg_propgraph_label_property.dat */


#endif							/* PG_PROPGRAPH_LABEL_PROPERTY_D_H */
