# Copyright (c) 2022-2025, PostgreSQL Global Development Group

backend_sources += files(
  'recno_fsm.c',
  'recno_handler.c',
  'recno_hlc.c',
  'recno_operations.c',
  'recno_overflow.c',
  'recno_tuple.c',
  'recno_mvcc.c',
  'recno_compress.c',
  'recno_stats.c',
  'recno_xlog.c',
  'recno_lock.c',
  'recno_slot.c',
  'recno_vm.c',
  'recno_clock.c',
  'recno_diff.c',
  'recno_slog.c',
  'recno_undo.c',
)