# Copyright (c) 2022-2026, PostgreSQL Global Development Group

tests += {
  'name': 'subscription',
  'sd': meson.current_source_dir(),
  'bd': meson.current_build_dir(),
  'tap': {
    'env': {
      'with_icu': icu.found() ? 'yes' : 'no',
      'enable_injection_points': get_option('injection_points') ? 'yes' : 'no',
    },
    'tests': [
      't/001_rep_changes.pl',
      't/002_types.pl',
      't/003_constraints.pl',
      't/004_sync.pl',
      't/005_encoding.pl',
      't/006_rewrite.pl',
      't/007_ddl.pl',
      't/008_diff_schema.pl',
      't/009_matviews.pl',
      't/010_truncate.pl',
      't/011_generated.pl',
      't/012_collation.pl',
      't/013_partition.pl',
      't/014_binary.pl',
      't/015_stream.pl',
      't/016_stream_subxact.pl',
      't/017_stream_ddl.pl',
      't/018_stream_subxact_abort.pl',
      't/019_stream_subxact_ddl_abort.pl',
      't/020_messages.pl',
      't/021_twophase.pl',
      't/022_twophase_cascade.pl',
      't/023_twophase_stream.pl',
      't/024_add_drop_pub.pl',
      't/025_rep_changes_for_schema.pl',
      't/026_stats.pl',
      't/027_nosuperuser.pl',
      't/028_row_filter.pl',
      't/029_on_error.pl',
      't/030_origin.pl',
      't/031_column_list.pl',
      't/032_subscribe_use_index.pl',
      't/033_run_as_table_owner.pl',
      't/034_temporal.pl',
      't/035_conflicts.pl',
      't/036_sequences.pl',
      't/037_except.pl',
      't/038_walsnd_shutdown_timeout.pl',
      't/100_bugs.pl',
    ],
  },
  'pytest': {
    'env': {
       'enable_injection_points': get_option('injection_points') ? 'yes' : 'no',
       'with_icu': icu.found() ? 'yes' : 'no',
    },
    'tests': [
      'pyt/test_002_types.py',
      'pyt/test_001_rep_changes.py',
      'pyt/test_003_constraints.py',
      'pyt/test_004_sync.py',
      'pyt/test_005_encoding.py',
      'pyt/test_006_rewrite.py',
      'pyt/test_007_ddl.py',
      'pyt/test_008_diff_schema.py',
      'pyt/test_009_matviews.py',
      'pyt/test_010_truncate.py',
      'pyt/test_011_generated.py',
      'pyt/test_012_collation.py',
      'pyt/test_013_partition.py',
      'pyt/test_014_binary.py',
      'pyt/test_016_stream_subxact.py',
      'pyt/test_017_stream_ddl.py',
      'pyt/test_018_stream_subxact_abort.py',
      'pyt/test_019_stream_subxact_ddl_abort.py',
      'pyt/test_020_messages.py',
      'pyt/test_021_twophase.py',
      'pyt/test_022_twophase_cascade.py',
      'pyt/test_023_twophase_stream.py',
      'pyt/test_024_add_drop_pub.py',
      'pyt/test_027_nosuperuser.py',
      'pyt/test_028_row_filter.py',
      'pyt/test_029_on_error.py',
      'pyt/test_030_origin.py',
      'pyt/test_031_column_list.py',
      'pyt/test_032_subscribe_use_index.py',
      'pyt/test_033_run_as_table_owner.py',
      'pyt/test_034_temporal.py',
      'pyt/test_036_sequences.py',
      'pyt/test_037_except.py',
      'pyt/test_025_rep_changes_for_schema.py',
      'pyt/test_026_stats.py',
      'pyt/test_038_walsnd_shutdown_timeout.py',
      'pyt/test_015_stream.py',
      'pyt/test_035_conflicts.py',
      'pyt/test_100_bugs.py',
    ],
  },
}
